#!/usr/bin/env php
<?php

/**
 * @package GPL Cart core
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */

if (PHP_SAPI !== 'cli') {
    echo("\033[31mOnly CLI access allowed!\033[0m\n");
    exit(1);
}

require 'system/bootstrap.php';
