<?php

namespace core\models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-06 at 18:37:23.
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $hook = $this->getMockBuilder('core\\Hook')->disableOriginalConstructor()->getMock();
        $config = $this->getMockBuilder('core\\Config')->disableOriginalConstructor()->getMock();
        $country = $this->getMockBuilder('core\\models\\Country')->disableOriginalConstructor()->getMock();
        
        $config->setDb(222);
        
        $this->object = new Address($country, $hook, $config);
        
        
        
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers core\models\Address::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $this->assertTrue(true);
    }

}
