<?php

/**
 * @package GPL Cart core
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    'AF' => array('name' => /* @text */'Afghanistan'),
    'AX' => array('name' => /* @text */'Aland Islands'),
    'AL' => array('name' => /* @text */'Albania'),
    'DZ' => array('name' => /* @text */'Algeria'),
    'AS' => array('name' => /* @text */'American Samoa'),
    'AD' => array('name' => /* @text */'Andorra'),
    'AO' => array('name' => /* @text */'Angola'),
    'AI' => array('name' => /* @text */'Anguilla'),
    'AQ' => array('name' => /* @text */'Antarctica'),
    'AG' => array('name' => /* @text */'Antigua and Barbuda'),
    'AR' => array('name' => /* @text */'Argentina'),
    'AM' => array('name' => /* @text */'Armenia'),
    'AW' => array('name' => /* @text */'Aruba'),
    'AU' => array('name' => /* @text */'Australia'),
    'AT' => array('name' => /* @text */'Austria'),
    'AZ' => array('name' => /* @text */'Azerbaijan'),
    'BS' => array('name' => /* @text */'Bahamas'),
    'BH' => array('name' => /* @text */'Bahrain'),
    'BD' => array('name' => /* @text */'Bangladesh'),
    'BB' => array('name' => /* @text */'Barbados'),
    'BY' => array('name' => /* @text */'Belarus'),
    'BE' => array('name' => /* @text */'Belgium'),
    'BZ' => array('name' => /* @text */'Belize'),
    'BJ' => array('name' => /* @text */'Benin'),
    'BM' => array('name' => /* @text */'Bermuda'),
    'BT' => array('name' => /* @text */'Bhutan'),
    'BO' => array('name' => /* @text */'Bolivia'),
    'BQ' => array('name' => /* @text */'Bonaire, Saint Eustatius and Saba'),
    'BA' => array('name' => /* @text */'Bosnia and Herzegovina'),
    'BW' => array('name' => /* @text */'Botswana'),
    'BV' => array('name' => /* @text */'Bouvet Island'),
    'BR' => array('name' => /* @text */'Brazil'),
    'IO' => array('name' => /* @text */'British Indian Ocean Territory'),
    'VG' => array('name' => /* @text */'British Virgin Islands'),
    'BN' => array('name' => /* @text */'Brunei'),
    'BG' => array('name' => /* @text */'Bulgaria'),
    'BF' => array('name' => /* @text */'Burkina Faso'),
    'BI' => array('name' => /* @text */'Burundi'),
    'KH' => array('name' => /* @text */'Cambodia'),
    'CM' => array('name' => /* @text */'Cameroon'),
    'CA' => array('name' => /* @text */'Canada'),
    'CV' => array('name' => /* @text */'Cape Verde'),
    'KY' => array('name' => /* @text */'Cayman Islands'),
    'CF' => array('name' => /* @text */'Central African Republic'),
    'TD' => array('name' => /* @text */'Chad'),
    'CL' => array('name' => /* @text */'Chile'),
    'CN' => array('name' => /* @text */'China'),
    'CX' => array('name' => /* @text */'Christmas Island'),
    'CC' => array('name' => /* @text */'Cocos Islands'),
    'CO' => array('name' => /* @text */'Colombia'),
    'KM' => array('name' => /* @text */'Comoros'),
    'CK' => array('name' => /* @text */'Cook Islands'),
    'CR' => array('name' => /* @text */'Costa Rica'),
    'HR' => array('name' => /* @text */'Croatia'),
    'CU' => array('name' => /* @text */'Cuba'),
    'CW' => array('name' => /* @text */'Curacao'),
    'CY' => array('name' => /* @text */'Cyprus'),
    'CZ' => array('name' => /* @text */'Czech Republic'),
    'CD' => array('name' => /* @text */'Democratic Republic of the Congo'),
    'DK' => array('name' => /* @text */'Denmark'),
    'DJ' => array('name' => /* @text */'Djibouti'),
    'DM' => array('name' => /* @text */'Dominica'),
    'DO' => array('name' => /* @text */'Dominican Republic'),
    'TL' => array('name' => /* @text */'East Timor'),
    'EC' => array('name' => /* @text */'Ecuador'),
    'EG' => array('name' => /* @text */'Egypt'),
    'SV' => array('name' => /* @text */'El Salvador'),
    'GQ' => array('name' => /* @text */'Equatorial Guinea'),
    'ER' => array('name' => /* @text */'Eritrea'),
    'EE' => array('name' => /* @text */'Estonia'),
    'ET' => array('name' => /* @text */'Ethiopia'),
    'FK' => array('name' => /* @text */'Falkland Islands'),
    'FO' => array('name' => /* @text */'Faroe Islands'),
    'FJ' => array('name' => /* @text */'Fiji'),
    'FI' => array('name' => /* @text */'Finland'),
    'FR' => array('name' => /* @text */'France'),
    'GF' => array('name' => /* @text */'French Guiana'),
    'PF' => array('name' => /* @text */'French Polynesia'),
    'TF' => array('name' => /* @text */'French Southern Territories'),
    'GA' => array('name' => /* @text */'Gabon'),
    'GM' => array('name' => /* @text */'Gambia'),
    'GE' => array('name' => /* @text */'Georgia'),
    'DE' => array('name' => /* @text */'Germany'),
    'GH' => array('name' => /* @text */'Ghana'),
    'GI' => array('name' => /* @text */'Gibraltar'),
    'GR' => array('name' => /* @text */'Greece'),
    'GL' => array('name' => /* @text */'Greenland'),
    'GD' => array('name' => /* @text */'Grenada'),
    'GP' => array('name' => /* @text */'Guadeloupe'),
    'GU' => array('name' => /* @text */'Guam'),
    'GT' => array('name' => /* @text */'Guatemala'),
    'GG' => array('name' => /* @text */'Guernsey'),
    'GN' => array('name' => /* @text */'Guinea'),
    'GW' => array('name' => /* @text */'Guinea-Bissau'),
    'GY' => array('name' => /* @text */'Guyana'),
    'HT' => array('name' => /* @text */'Haiti'),
    'HM' => array('name' => /* @text */'Heard Island and McDonald Islands'),
    'HN' => array('name' => /* @text */'Honduras'),
    'HK' => array('name' => /* @text */'Hong Kong'),
    'HU' => array('name' => /* @text */'Hungary'),
    'IS' => array('name' => /* @text */'Iceland'),
    'IN' => array('name' => /* @text */'India'),
    'ID' => array('name' => /* @text */'Indonesia'),
    'IR' => array('name' => /* @text */'Iran'),
    'IQ' => array('name' => /* @text */'Iraq'),
    'IE' => array('name' => /* @text */'Ireland'),
    'IM' => array('name' => /* @text */'Isle of Man'),
    'IL' => array('name' => /* @text */'Israel'),
    'IT' => array('name' => /* @text */'Italy'),
    'CI' => array('name' => /* @text */'Ivory Coast'),
    'JM' => array('name' => /* @text */'Jamaica'),
    'JP' => array('name' => /* @text */'Japan'),
    'JE' => array('name' => /* @text */'Jersey'),
    'JO' => array('name' => /* @text */'Jordan'),
    'KZ' => array('name' => /* @text */'Kazakhstan'),
    'KE' => array('name' => /* @text */'Kenya'),
    'KI' => array('name' => /* @text */'Kiribati'),
    'XK' => array('name' => /* @text */'Kosovo'),
    'KW' => array('name' => /* @text */'Kuwait'),
    'KG' => array('name' => /* @text */'Kyrgyzstan'),
    'LA' => array('name' => /* @text */'Laos'),
    'LV' => array('name' => /* @text */'Latvia'),
    'LB' => array('name' => /* @text */'Lebanon'),
    'LS' => array('name' => /* @text */'Lesotho'),
    'LR' => array('name' => /* @text */'Liberia'),
    'LY' => array('name' => /* @text */'Libya'),
    'LI' => array('name' => /* @text */'Liechtenstein'),
    'LT' => array('name' => /* @text */'Lithuania'),
    'LU' => array('name' => /* @text */'Luxembourg'),
    'MO' => array('name' => /* @text */'Macao'),
    'MK' => array('name' => /* @text */'Macedonia'),
    'MG' => array('name' => /* @text */'Madagascar'),
    'MW' => array('name' => /* @text */'Malawi'),
    'MY' => array('name' => /* @text */'Malaysia'),
    'MV' => array('name' => /* @text */'Maldives'),
    'ML' => array('name' => /* @text */'Mali'),
    'MT' => array('name' => /* @text */'Malta'),
    'MH' => array('name' => /* @text */'Marshall Islands'),
    'MQ' => array('name' => /* @text */'Martinique'),
    'MR' => array('name' => /* @text */'Mauritania'),
    'MU' => array('name' => /* @text */'Mauritius'),
    'YT' => array('name' => /* @text */'Mayotte'),
    'MX' => array('name' => /* @text */'Mexico'),
    'FM' => array('name' => /* @text */'Micronesia'),
    'MD' => array('name' => /* @text */'Moldova'),
    'MC' => array('name' => /* @text */'Monaco'),
    'MN' => array('name' => /* @text */'Mongolia'),
    'ME' => array('name' => /* @text */'Montenegro'),
    'MS' => array('name' => /* @text */'Montserrat'),
    'MA' => array('name' => /* @text */'Morocco'),
    'MZ' => array('name' => /* @text */'Mozambique'),
    'MM' => array('name' => /* @text */'Myanmar'),
    'NA' => array('name' => /* @text */'Namibia'),
    'NR' => array('name' => /* @text */'Nauru'),
    'NP' => array('name' => /* @text */'Nepal'),
    'NL' => array('name' => /* @text */'Netherlands'),
    'NC' => array('name' => /* @text */'New Caledonia'),
    'NZ' => array('name' => /* @text */'New Zealand'),
    'NI' => array('name' => /* @text */'Nicaragua'),
    'NE' => array('name' => /* @text */'Niger'),
    'NG' => array('name' => /* @text */'Nigeria'),
    'NU' => array('name' => /* @text */'Niue'),
    'NF' => array('name' => /* @text */'Norfolk Island'),
    'KP' => array('name' => /* @text */'North Korea'),
    'MP' => array('name' => /* @text */'Northern Mariana Islands'),
    'NO' => array('name' => /* @text */'Norway'),
    'OM' => array('name' => /* @text */'Oman'),
    'PK' => array('name' => /* @text */'Pakistan'),
    'PW' => array('name' => /* @text */'Palau'),
    'PS' => array('name' => /* @text */'Palestinian Territory'),
    'PA' => array('name' => /* @text */'Panama'),
    'PG' => array('name' => /* @text */'Papua New Guinea'),
    'PY' => array('name' => /* @text */'Paraguay'),
    'PE' => array('name' => /* @text */'Peru'),
    'PH' => array('name' => /* @text */'Philippines'),
    'PN' => array('name' => /* @text */'Pitcairn'),
    'PL' => array('name' => /* @text */'Poland'),
    'PT' => array('name' => /* @text */'Portugal'),
    'PR' => array('name' => /* @text */'Puerto Rico'),
    'QA' => array('name' => /* @text */'Qatar'),
    'CG' => array('name' => /* @text */'Republic of the Congo'),
    'RE' => array('name' => /* @text */'Reunion'),
    'RO' => array('name' => /* @text */'Romania'),
    'RU' => array('name' => /* @text */'Russia'),
    'RW' => array('name' => /* @text */'Rwanda'),
    'BL' => array('name' => /* @text */'Saint Barthelemy'),
    'SH' => array('name' => /* @text */'Saint Helena'),
    'KN' => array('name' => /* @text */'Saint Kitts and Nevis'),
    'LC' => array('name' => /* @text */'Saint Lucia'),
    'MF' => array('name' => /* @text */'Saint Martin'),
    'PM' => array('name' => /* @text */'Saint Pierre and Miquelon'),
    'VC' => array('name' => /* @text */'Saint Vincent and the Grenadines'),
    'WS' => array('name' => /* @text */'Samoa'),
    'SM' => array('name' => /* @text */'San Marino'),
    'ST' => array('name' => /* @text */'Sao Tome and Principe'),
    'SA' => array('name' => /* @text */'Saudi Arabia'),
    'SN' => array('name' => /* @text */'Senegal'),
    'RS' => array('name' => /* @text */'Serbia'),
    'SC' => array('name' => /* @text */'Seychelles'),
    'SL' => array('name' => /* @text */'Sierra Leone'),
    'SG' => array('name' => /* @text */'Singapore'),
    'SX' => array('name' => /* @text */'Sint Maarten'),
    'SK' => array('name' => /* @text */'Slovakia'),
    'SI' => array('name' => /* @text */'Slovenia'),
    'SB' => array('name' => /* @text */'Solomon Islands'),
    'SO' => array('name' => /* @text */'Somalia'),
    'ZA' => array('name' => /* @text */'South Africa'),
    'GS' => array('name' => /* @text */'South Georgia and the South Sandwich Islands'),
    'KR' => array('name' => /* @text */'South Korea'),
    'SS' => array('name' => /* @text */'South Sudan'),
    'ES' => array('name' => /* @text */'Spain'),
    'LK' => array('name' => /* @text */'Sri Lanka'),
    'SD' => array('name' => /* @text */'Sudan'),
    'SR' => array('name' => /* @text */'Suriname'),
    'SJ' => array('name' => /* @text */'Svalbard and Jan Mayen'),
    'SZ' => array('name' => /* @text */'Swaziland'),
    'SE' => array('name' => /* @text */'Sweden'),
    'CH' => array('name' => /* @text */'Switzerland'),
    'SY' => array('name' => /* @text */'Syria'),
    'TW' => array('name' => /* @text */'Taiwan'),
    'TJ' => array('name' => /* @text */'Tajikistan'),
    'TZ' => array('name' => /* @text */'Tanzania'),
    'TH' => array('name' => /* @text */'Thailand'),
    'TG' => array('name' => /* @text */'Togo'),
    'TK' => array('name' => /* @text */'Tokelau'),
    'TO' => array('name' => /* @text */'Tonga'),
    'TT' => array('name' => /* @text */'Trinidad and Tobago'),
    'TN' => array('name' => /* @text */'Tunisia'),
    'TR' => array('name' => /* @text */'Turkey'),
    'TM' => array('name' => /* @text */'Turkmenistan'),
    'TC' => array('name' => /* @text */'Turks and Caicos Islands'),
    'TV' => array('name' => /* @text */'Tuvalu'),
    'VI' => array('name' => /* @text */'U.S. Virgin Islands'),
    'UG' => array('name' => /* @text */'Uganda'),
    'UA' => array('name' => /* @text */'Ukraine'),
    'AE' => array('name' => /* @text */'United Arab Emirates'),
    'GB' => array('name' => /* @text */'United Kingdom'),
    'US' => array('name' => /* @text */'United States'),
    'UM' => array('name' => /* @text */'United States Minor Outlying Islands'),
    'UY' => array('name' => /* @text */'Uruguay'),
    'UZ' => array('name' => /* @text */'Uzbekistan'),
    'VU' => array('name' => /* @text */'Vanuatu'),
    'VA' => array('name' => /* @text */'Vatican'),
    'VE' => array('name' => /* @text */'Venezuela'),
    'VN' => array('name' => /* @text */'Vietnam'),
    'WF' => array('name' => /* @text */'Wallis and Futuna'),
    'EH' => array('name' => /* @text */'Western Sahara'),
    'YE' => array('name' => /* @text */'Yemen'),
    'ZM' => array('name' => /* @text */'Zambia'),
    'ZW' => array('name' => /* @text */'Zimbabwe')
);
