<?php

/**
 * @package GPL Cart core
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    'USD' => array(
        'symbol' => '$',
        'name' => /* @text */'United States Dollar',
        'numeric_code' => '840',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'AED' => array(
        'symbol' => 'د.إ',
        'name' => /* @text */'United Arab Emirates Dirham',
        'numeric_code' => '784',
        'minor_unit' => /* @text */'Fils',
        'major_unit' => /* @text */'Dirham',
    ),
    'AFN' => array(
        'symbol' => 'Af',
        'name' => /* @text */'Afghan Afghani',
        'decimals' => 0,
        'numeric_code' => '971',
        'minor_unit' => /* @text */'Pul',
        'major_unit' => /* @text */'Afghani',
    ),
    'ANG' => array(
        'symbol' => 'NAf.',
        'name' => /* @text */'Netherlands Antillean Guilder',
        'numeric_code' => '532',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Guilder',
    ),
    'AOA' => array(
        'symbol' => 'Kz',
        'name' => /* @text */'Angolan Kwanza',
        'numeric_code' => '973',
        'minor_unit' => /* @text */'Cêntimo',
        'major_unit' => /* @text */'Kwanza',
    ),
    'ARM' => array(
        'symbol' => 'm$n',
        'name' => /* @text */'Argentine Peso Moneda Nacional',
        'minor_unit' => /* @text */'Centavos',
        'major_unit' => /* @text */'Peso',
    ),
    'ARS' => array(
        'symbol' => 'AR$',
        'name' => /* @text */'Argentine Peso',
        'numeric_code' => '032',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'AUD' => array(
        'symbol' => '$',
        'name' => /* @text */'Australian Dollar',
        'numeric_code' => '036',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'AWG' => array(
        'symbol' => 'Afl.',
        'name' => /* @text */'Aruban Florin',
        'numeric_code' => '533',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Guilder',
    ),
    'AZN' => array(
        'symbol' => 'man.',
        'name' => /* @text */'Azerbaijanian Manat',
        'minor_unit' => /* @text */'Qəpik',
        'major_unit' => /* @text */'New Manat',
    ),
    'BAM' => array(
        'symbol' => 'KM',
        'name' => /* @text */'Bosnia-Herzegovina Convertible Mark',
        'numeric_code' => '977',
        'minor_unit' => /* @text */'Fening',
        'major_unit' => /* @text */'Convertible Marka',
    ),
    'BBD' => array(
        'symbol' => 'Bds$',
        'name' => /* @text */'Barbadian Dollar',
        'numeric_code' => '052',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'BDT' => array(
        'symbol' => 'Tk',
        'name' => /* @text */'Bangladeshi Taka',
        'numeric_code' => '050',
        'minor_unit' => /* @text */'Paisa',
        'major_unit' => /* @text */'Taka',
    ),
    'BGN' => array(
        'symbol' => 'лв',
        'name' => /* @text */'Bulgarian lev',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '975',
        'minor_unit' => /* @text */'Stotinka',
        'major_unit' => /* @text */'Lev',
    ),
    'BHD' => array(
        'symbol' => 'BD',
        'name' => /* @text */'Bahraini Dinar',
        'decimals' => 3,
        'numeric_code' => '048',
        'minor_unit' => /* @text */'Fils',
        'major_unit' => /* @text */'Dinar',
    ),
    'BIF' => array(
        'symbol' => 'FBu',
        'name' => /* @text */'Burundian Franc',
        'decimals' => 0,
        'numeric_code' => '108',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'BMD' => array(
        'symbol' => 'BD$',
        'name' => /* @text */'Bermudan Dollar',
        'numeric_code' => '060',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'BND' => array(
        'symbol' => 'BN$',
        'name' => /* @text */'Brunei Dollar',
        'numeric_code' => '096',
        'minor_unit' => /* @text */'Sen',
        'major_unit' => /* @text */'Dollar',
    ),
    'BOB' => array(
        'symbol' => 'Bs',
        'name' => /* @text */'Bolivian Boliviano',
        'numeric_code' => '068',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Bolivianos',
    ),
    'BRL' => array(
        'symbol' => 'R$',
        'name' => /* @text */'Brazilian Real',
        'numeric_code' => '986',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Reais',
    ),
    'BSD' => array(
        'symbol' => 'BS$',
        'name' => /* @text */'Bahamian Dollar',
        'numeric_code' => '044',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'BTN' => array(
        'symbol' => 'Nu.',
        'name' => /* @text */'Bhutanese Ngultrum',
        'numeric_code' => '064',
        'minor_unit' => /* @text */'Chetrum',
        'major_unit' => /* @text */'Ngultrum',
    ),
    'BWP' => array(
        'symbol' => 'BWP',
        'name' => /* @text */'Botswanan Pula',
        'numeric_code' => '072',
        'minor_unit' => /* @text */'Thebe',
        'major_unit' => /* @text */'Pulas',
    ),
    'BYR' => array(
        'symbol' => 'руб.',
        'name' => /* @text */'Belarusian ruble',
        'numeric_code' => '974',
        'decimals' => 0,
        'thousands_separator' => ' ',
        'major_unit' => /* @text */'Ruble',
    ),
    'BZD' => array(
        'symbol' => 'BZ$',
        'name' => /* @text */'Belize Dollar',
        'numeric_code' => '084',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'CAD' => array(
        'symbol' => '$',
        'name' => /* @text */'Canadian Dollar',
        'numeric_code' => '124',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'CDF' => array(
        'symbol' => 'CDF',
        'name' => /* @text */'Congolese Franc',
        'numeric_code' => '976',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'CHF' => array(
        'symbol' => 'Fr.',
        'name' => /* @text */'Swiss Franc',
        'rounding_step' => '0.05',
        'numeric_code' => '756',
        'thousands_separator' => "'",
        'minor_unit' => /* @text */'Rappen',
        'major_unit' => /* @text */'Franc',
    ),
    'CLP' => array(
        'symbol' => 'CL$',
        'name' => /* @text */'Chilean Peso',
        'decimals' => 0,
        'numeric_code' => '152',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'CNY' => array(
        'symbol' => '¥',
        'name' => /* @text */'Chinese Yuan Renminbi',
        'numeric_code' => '156',
        'thousands_separator' => '',
        'minor_unit' => /* @text */'Fen',
        'major_unit' => /* @text */'Yuan',
    ),
    'COP' => array(
        'symbol' => '$',
        'name' => /* @text */'Colombian Peso',
        'decimals' => 0,
        'numeric_code' => '170',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'CRC' => array(
        'symbol' => '¢',
        'name' => /* @text */'Costa Rican Colón',
        'decimals' => 0,
        'numeric_code' => '188',
        'minor_unit' => /* @text */'Céntimo',
        'major_unit' => /* @text */'Colón',
    ),
    'CUC' => array(
        'symbol' => 'CUC$',
        'name' => /* @text */'Cuban Convertible Peso',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'CUP' => array(
        'symbol' => 'CU$',
        'name' => /* @text */'Cuban Peso',
        'numeric_code' => '192',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'CVE' => array(
        'symbol' => 'CV$',
        'name' => /* @text */'Cape Verdean Escudo',
        'numeric_code' => '132',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Escudo',
    ),
    'CZK' => array(
        'symbol' => 'Kč',
        'name' => /* @text */'Czech Republic Koruna',
        'numeric_code' => '203',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Haléř',
        'major_unit' => /* @text */'Koruna',
    ),
    'DJF' => array(
        'symbol' => 'Fdj',
        'name' => /* @text */'Djiboutian Franc',
        'numeric_code' => '262',
        'decimals' => 0,
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'DKK' => array(
        'symbol' => 'kr.',
        'name' => /* @text */'Danish Krone',
        'numeric_code' => '208',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Øre',
        'major_unit' => /* @text */'Kroner',
    ),
    'DOP' => array(
        'symbol' => 'RD$',
        'name' => /* @text */'Dominican Peso',
        'numeric_code' => '214',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'DZD' => array(
        'symbol' => 'DA',
        'name' => /* @text */'Algerian Dinar',
        'numeric_code' => '012',
        'minor_unit' => /* @text */'Santeem',
        'major_unit' => /* @text */'Dinar',
    ),
    'EEK' => array(
        'symbol' => 'Ekr',
        'name' => /* @text */'Estonian Kroon',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '233',
        'minor_unit' => /* @text */'Sent',
        'major_unit' => /* @text */'Krooni',
    ),
    'EGP' => array(
        'symbol' => 'EG£',
        'name' => /* @text */'Egyptian Pound',
        'numeric_code' => '818',
        'minor_unit' => /* @text */'Piastr',
        'major_unit' => /* @text */'Pound',
    ),
    'ERN' => array(
        'symbol' => 'Nfk',
        'name' => /* @text */'Eritrean Nakfa',
        'numeric_code' => '232',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Nakfa',
    ),
    'ETB' => array(
        'symbol' => 'Br',
        'name' => /* @text */'Ethiopian Birr',
        'numeric_code' => '230',
        'minor_unit' => /* @text */'Santim',
        'major_unit' => /* @text */'Birr',
    ),
    'EUR' => array(
        'symbol' => '€',
        'name' => /* @text */'Euro',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '978',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Euro',
    ),
    'FJD' => array(
        'symbol' => 'FJ$',
        'name' => /* @text */'Fijian Dollar',
        'numeric_code' => '242',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'FKP' => array(
        'symbol' => 'FK£',
        'name' => /* @text */'Falkland Islands Pound',
        'numeric_code' => '238',
        'minor_unit' => /* @text */'Penny',
        'major_unit' => /* @text */'Pound',
    ),
    'GBP' => array(
        'symbol' => '£',
        'name' => /* @text */'British Pound Sterling',
        'numeric_code' => '826',
        'minor_unit' => /* @text */'Penny',
        'major_unit' => /* @text */'Pound',
    ),
    'GHS' => array(
        'symbol' => 'GH₵',
        'name' => /* @text */'Ghanaian Cedi',
        'minor_unit' => /* @text */'Pesewa',
        'major_unit' => /* @text */'Cedi',
    ),
    'GIP' => array(
        'symbol' => 'GI£',
        'name' => /* @text */'Gibraltar Pound',
        'numeric_code' => '292',
        'minor_unit' => /* @text */'Penny',
        'major_unit' => /* @text */'Pound',
    ),
    'GMD' => array(
        'symbol' => 'GMD',
        'name' => /* @text */'Gambian Dalasi',
        'numeric_code' => '270',
        'minor_unit' => /* @text */'Butut',
        'major_unit' => /* @text */'Dalasis',
    ),
    'GNF' => array(
        'symbol' => 'FG',
        'name' => /* @text */'Guinean Franc',
        'decimals' => 0,
        'numeric_code' => '324',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'GTQ' => array(
        'symbol' => 'GTQ',
        'name' => /* @text */'Guatemalan Quetzal',
        'numeric_code' => '320',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Quetzales',
    ),
    'GYD' => array(
        'symbol' => 'GY$',
        'name' => /* @text */'Guyanaese Dollar',
        'decimals' => 0,
        'numeric_code' => '328',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'HKD' => array(
        'symbol' => 'HK$',
        'name' => /* @text */'Hong Kong Dollar',
        'numeric_code' => '344',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'HNL' => array(
        'symbol' => 'HNL',
        'name' => /* @text */'Honduran Lempira',
        'numeric_code' => '340',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Lempiras',
    ),
    'HRK' => array(
        'symbol' => 'kn',
        'name' => /* @text */'Croatian Kuna',
        'numeric_code' => '191',
        'minor_unit' => /* @text */'Lipa',
        'major_unit' => /* @text */'Kuna',
    ),
    'HTG' => array(
        'symbol' => 'HTG',
        'name' => /* @text */'Haitian Gourde',
        'numeric_code' => '332',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Gourde',
    ),
    'HUF' => array(
        'symbol' => 'Ft',
        'name' => /* @text */'Hungarian Forint',
        'numeric_code' => '348',
        'decimal_separator' => ',',
        'thousands_separator' => ' ',
        'decimals' => 0,
        'major_unit' => /* @text */'Forint',
    ),
    'IDR' => array(
        'symbol' => 'Rp',
        'name' => /* @text */'Indonesian Rupiah',
        'decimals' => 0,
        'numeric_code' => '360',
        'minor_unit' => /* @text */'Sen',
        'major_unit' => /* @text */'Rupiahs',
    ),
    'ILS' => array(
        'symbol' => '₪',
        'name' => /* @text */'Israeli New Shekel',
        'numeric_code' => '376',
        'minor_unit' => /* @text */'Agora',
        'major_unit' => /* @text */'New Shekels',
    ),
    'INR' => array(
        'symbol' => 'Rs',
        'name' => /* @text */'Indian Rupee',
        'numeric_code' => '356',
        'minor_unit' => /* @text */'Paisa',
        'major_unit' => /* @text */'Rupee',
    ),
    'IRR' => array(
        'symbol' => 'ریال',
        'name' => /* @text */'Iranian Rial',
        'decimals' => 0,
        'numeric_code' => '364',
        'minor_unit' => /* @text */'Rial',
        'major_unit' => /* @text */'Toman',
    ),
    'ISK' => array(
        'symbol' => 'Ikr',
        'name' => /* @text */'Icelandic Króna',
        'decimals' => 0,
        'thousands_separator' => ' ',
        'numeric_code' => '352',
        'minor_unit' => /* @text */'Eyrir',
        'major_unit' => /* @text */'Kronur',
    ),
    'JMD' => array(
        'symbol' => 'J$',
        'name' => /* @text */'Jamaican Dollar',
        'numeric_code' => '388',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'JOD' => array(
        'symbol' => 'JD',
        'name' => /* @text */'Jordanian Dinar',
        'decimals' => 3,
        'numeric_code' => '400',
        'minor_unit' => /* @text */'Piastr',
        'major_unit' => /* @text */'Dinar',
    ),
    'JPY' => array(
        'symbol' => '¥',
        'name' => /* @text */'Japanese Yen',
        'decimals' => 0,
        'numeric_code' => '392',
        'minor_unit' => /* @text */'Sen',
        'major_unit' => /* @text */'Yen',
    ),
    'KES' => array(
        'symbol' => 'Ksh',
        'name' => /* @text */'Kenyan Shilling',
        'numeric_code' => '404',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Shilling',
    ),
    'KGS' => array(
        'symbol' => 'сом',
        'name' => /* @text */'Kyrgyzstani Som',
        'numeric_code' => '417',
        'thousands_separator' => '',
        'major_unit' => /* @text */'Som',
        'minor_unit' => /* @text */'Tyiyn',
    ),
    'KMF' => array(
        'symbol' => 'CF',
        'name' => /* @text */'Comorian Franc',
        'decimals' => 0,
        'numeric_code' => '174',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'KRW' => array(
        'symbol' => '₩',
        'name' => /* @text */'South Korean Won',
        'decimals' => 0,
        'numeric_code' => '410',
        'minor_unit' => /* @text */'Jeon',
        'major_unit' => /* @text */'Won',
    ),
    'KWD' => array(
        'symbol' => 'KD',
        'name' => /* @text */'Kuwaiti Dinar',
        'decimals' => 3,
        'numeric_code' => '414',
        'minor_unit' => /* @text */'Fils',
        'major_unit' => /* @text */'Dinar',
    ),
    'KYD' => array(
        'symbol' => 'KY$',
        'name' => /* @text */'Cayman Islands Dollar',
        'numeric_code' => '136',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'KZT' => array(
        'symbol' => 'тг.',
        'name' => /* @text */'Kazakhstani tenge',
        'numeric_code' => '398',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Tiyn',
        'major_unit' => /* @text */'Tenge',
    ),
    'LAK' => array(
        'symbol' => '₭N',
        'name' => /* @text */'Laotian Kip',
        'decimals' => 0,
        'numeric_code' => '418',
        'minor_unit' => /* @text */'Att',
        'major_unit' => /* @text */'Kips',
    ),
    'LBP' => array(
        'symbol' => 'LB£',
        'name' => /* @text */'Lebanese Pound',
        'decimals' => 0,
        'numeric_code' => '422',
        'minor_unit' => /* @text */'Piastre',
        'major_unit' => /* @text */'Pound',
    ),
    'LKR' => array(
        'symbol' => 'SLRs',
        'name' => /* @text */'Sri Lanka Rupee',
        'numeric_code' => '144',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Rupee',
    ),
    'LRD' => array(
        'symbol' => 'L$',
        'name' => /* @text */'Liberian Dollar',
        'numeric_code' => '430',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'LSL' => array(
        'symbol' => 'LSL',
        'name' => /* @text */'Lesotho Loti',
        'numeric_code' => '426',
        'minor_unit' => /* @text */'Sente',
        'major_unit' => /* @text */'Loti',
    ),
    'LTL' => array(
        'symbol' => 'Lt',
        'name' => /* @text */'Lithuanian Litas',
        'numeric_code' => '440',
        'minor_unit' => /* @text */'Centas',
        'major_unit' => /* @text */'Litai',
    ),
    'LVL' => array(
        'symbol' => 'Ls',
        'name' => /* @text */'Latvian Lats',
        'numeric_code' => '428',
        'minor_unit' => /* @text */'Santims',
        'major_unit' => /* @text */'Lati',
    ),
    'LYD' => array(
        'symbol' => 'LD',
        'name' => /* @text */'Libyan Dinar',
        'decimals' => 3,
        'numeric_code' => '434',
        'minor_unit' => /* @text */'Dirham',
        'major_unit' => /* @text */'Dinar',
    ),
    'MAD' => array(
        'symbol' => ' Dhs',
        'name' => /* @text */'Moroccan Dirham',
        'numeric_code' => '504',
        'minor_unit' => /* @text */'Santimat',
        'major_unit' => /* @text */'Dirhams',
    ),
    'MDL' => array(
        'symbol' => 'MDL',
        'name' => /* @text */'Moldovan leu',
        'numeric_code' => '498',
        'minor_unit' => /* @text */'Bani',
        'major_unit' => /* @text */'Lei',
    ),
    'MKD' => array(
        'symbol' => 'ден',
        'name' => /* @text */'Macedonian denar',
        'numeric_code' => '807',
        'minor_unit' => /* @text */'Deni',
        'major_unit' => /* @text */'Denari',
    ),
    'MMK' => array(
        'symbol' => 'MMK',
        'name' => /* @text */'Myanma Kyat',
        'decimals' => 0,
        'numeric_code' => '104',
        'minor_unit' => /* @text */'Pya',
        'major_unit' => /* @text */'Kyat',
    ),
    'MNT' => array(
        'symbol' => '₮',
        'name' => /* @text */'Mongolian Tugrik',
        'decimals' => 0,
        'numeric_code' => '496',
        'minor_unit' => /* @text */'Möngö',
        'major_unit' => /* @text */'Tugriks',
    ),
    'MOP' => array(
        'symbol' => 'MOP$',
        'name' => /* @text */'Macanese Pataca',
        'numeric_code' => '446',
        'minor_unit' => /* @text */'Avo',
        'major_unit' => /* @text */'Pataca',
    ),
    'MRO' => array(
        'symbol' => 'UM',
        'name' => /* @text */'Mauritanian Ouguiya',
        'decimals' => 0,
        'numeric_code' => '478',
        'minor_unit' => /* @text */'Khoums',
        'major_unit' => /* @text */'Ouguiya',
    ),
    'MTP' => array(
        'symbol' => 'MT£',
        'name' => /* @text */'Maltese Pound',
        'minor_unit' => /* @text */'Shilling',
        'major_unit' => /* @text */'Pound',
    ),
    'MUR' => array(
        'symbol' => 'MURs',
        'name' => /* @text */'Mauritian Rupee',
        'decimals' => 0,
        'numeric_code' => '480',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Rupee',
    ),
    'MXN' => array(
        'symbol' => '$',
        'name' => /* @text */'Mexican Peso',
        'numeric_code' => '484',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'MYR' => array(
        'symbol' => 'RM',
        'name' => /* @text */'Malaysian Ringgit',
        'numeric_code' => '458',
        'minor_unit' => /* @text */'Sen',
        'major_unit' => /* @text */'Ringgits',
    ),
    'MZN' => array(
        'symbol' => 'MTn',
        'name' => /* @text */'Mozambican Metical',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Metical',
    ),
    'NAD' => array(
        'symbol' => 'N$',
        'name' => /* @text */'Namibian Dollar',
        'numeric_code' => '516',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'NGN' => array(
        'symbol' => '₦',
        'name' => /* @text */'Nigerian Naira',
        'numeric_code' => '566',
        'minor_unit' => /* @text */'Kobo',
        'major_unit' => /* @text */'Naira',
    ),
    'NIO' => array(
        'symbol' => 'C$',
        'name' => /* @text */'Nicaraguan Cordoba Oro',
        'numeric_code' => '558',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Cordoba',
    ),
    'NOK' => array(
        'symbol' => 'Nkr',
        'name' => /* @text */'Norwegian Krone',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '578',
        'minor_unit' => /* @text */'Øre',
        'major_unit' => /* @text */'Krone',
    ),
    'NPR' => array(
        'symbol' => 'NPRs',
        'name' => /* @text */'Nepalese Rupee',
        'numeric_code' => '524',
        'minor_unit' => /* @text */'Paisa',
        'major_unit' => /* @text */'Rupee',
    ),
    'NZD' => array(
        'symbol' => '$',
        'name' => /* @text */'New Zealand Dollar',
        'numeric_code' => '554',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'PAB' => array(
        'symbol' => 'B/.',
        'name' => /* @text */'Panamanian Balboa',
        'numeric_code' => '590',
        'minor_unit' => /* @text */'Centésimo',
        'major_unit' => /* @text */'Balboa',
    ),
    'PEN' => array(
        'symbol' => 'S/.',
        'name' => /* @text */'Peruvian Nuevo Sol',
        'numeric_code' => '604',
        'minor_unit' => /* @text */'Céntimo',
        'major_unit' => /* @text */'Nuevos Sole',
    ),
    'PGK' => array(
        'symbol' => 'PGK',
        'name' => /* @text */'Papua New Guinean Kina',
        'numeric_code' => '598',
        'minor_unit' => /* @text */'Toea',
        'major_unit' => /* @text */'Kina ',
    ),
    'PHP' => array(
        'symbol' => '₱',
        'name' => /* @text */'Philippine Peso',
        'numeric_code' => '608',
        'minor_unit' => /* @text */'Centavo',
        'major_unit' => /* @text */'Peso',
    ),
    'PKR' => array(
        'symbol' => 'PKRs',
        'name' => /* @text */'Pakistani Rupee',
        'decimals' => 0,
        'numeric_code' => '586',
        'minor_unit' => /* @text */'Paisa',
        'major_unit' => /* @text */'Rupee',
    ),
    'PLN' => array(
        'symbol' => 'zł',
        'name' => /* @text */'Polish Złoty',
        'decimal_separator' => ',',
        'thousands_separator' => ' ',
        'numeric_code' => '985',
        'minor_unit' => /* @text */'Grosz',
        'major_unit' => /* @text */'Złotych',
    ),
    'PYG' => array(
        'symbol' => '₲',
        'name' => /* @text */'Paraguayan Guarani',
        'decimals' => 0,
        'numeric_code' => '600',
        'minor_unit' => /* @text */'Céntimo',
        'major_unit' => /* @text */'Guarani',
    ),
    'QAR' => array(
        'symbol' => 'QR',
        'name' => /* @text */'Qatari Rial',
        'numeric_code' => '634',
        'minor_unit' => /* @text */'Dirham',
        'major_unit' => /* @text */'Rial',
    ),
    'RHD' => array(
        'symbol' => 'RH$',
        'name' => /* @text */'Rhodesian Dollar',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'RON' => array(
        'symbol' => 'RON',
        'name' => /* @text */'Romanian Leu',
        'minor_unit' => /* @text */'Ban',
        'major_unit' => /* @text */'Leu',
    ),
    'RSD' => array(
        'symbol' => 'din.',
        'name' => /* @text */'Serbian Dinar',
        'decimals' => 0,
        'minor_unit' => /* @text */'Para',
        'major_unit' => /* @text */'Dinars',
    ),
    'RUB' => array(
        'symbol' => 'руб.',
        'name' => /* @text */'Russian Ruble',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '643',
        'minor_unit' => /* @text */'Kopek',
        'major_unit' => /* @text */'Ruble',
    ),
    'SAR' => array(
        'symbol' => 'SR',
        'name' => /* @text */'Saudi Riyal',
        'numeric_code' => '682',
        'minor_unit' => /* @text */'Hallallah',
        'major_unit' => /* @text */'Riyals',
    ),
    'SBD' => array(
        'symbol' => 'SI$',
        'name' => /* @text */'Solomon Islands Dollar',
        'numeric_code' => '090',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'SCR' => array(
        'symbol' => 'SRe',
        'name' => /* @text */'Seychellois Rupee',
        'numeric_code' => '690',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Rupee',
    ),
    'SDD' => array(
        'symbol' => 'LSd',
        'name' => /* @text */'Old Sudanese Dinar',
        'numeric_code' => '736',
        'minor_unit' => /* @text */'',
        'major_unit' => /* @text */'Dinar',
    ),
    'SEK' => array(
        'symbol' => 'kr',
        'name' => /* @text */'Swedish Krona',
        'numeric_code' => '752',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Öre',
        'major_unit' => /* @text */'Kronor',
    ),
    'SGD' => array(
        'symbol' => 'S$',
        'name' => /* @text */'Singapore Dollar',
        'numeric_code' => '702',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'SHP' => array(
        'symbol' => 'SH£',
        'name' => /* @text */'Saint Helena Pound',
        'numeric_code' => '654',
        'minor_unit' => /* @text */'Penny',
        'major_unit' => /* @text */'Pound',
    ),
    'SLL' => array(
        'symbol' => 'Le',
        'name' => /* @text */'Sierra Leonean Leone',
        'decimals' => 0,
        'numeric_code' => '694',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Leone',
    ),
    'SOS' => array(
        'symbol' => 'Ssh',
        'name' => /* @text */'Somali Shilling',
        'decimals' => 0,
        'numeric_code' => '706',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Shilling',
    ),
    'SRD' => array(
        'symbol' => 'SR$',
        'name' => /* @text */'Surinamese Dollar',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'SRG' => array(
        'symbol' => 'Sf',
        'name' => /* @text */'Suriname Guilder',
        'numeric_code' => '740',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Guilder',
    ),
    'STD' => array(
        'symbol' => 'Db',
        'name' => /* @text */'São Tomé and Príncipe Dobra',
        'decimals' => 0,
        'numeric_code' => '678',
        'minor_unit' => /* @text */'Cêntimo',
        'major_unit' => /* @text */'Dobra',
    ),
    'SYP' => array(
        'symbol' => 'SY£',
        'name' => /* @text */'Syrian Pound',
        'decimals' => 0,
        'numeric_code' => '760',
        'minor_unit' => /* @text */'Piastre',
        'major_unit' => /* @text */'Pound',
    ),
    'SZL' => array(
        'symbol' => 'SZL',
        'name' => /* @text */'Swazi Lilangeni',
        'numeric_code' => '748',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Lilangeni',
    ),
    'THB' => array(
        'symbol' => '฿',
        'name' => /* @text */'Thai Baht',
        'numeric_code' => '764',
        'minor_unit' => /* @text */'Satang',
        'major_unit' => /* @text */'Baht',
    ),
    'TND' => array(
        'symbol' => 'DT',
        'name' => /* @text */'Tunisian Dinar',
        'decimals' => 3,
        'numeric_code' => '788',
        'minor_unit' => /* @text */'Millime',
        'major_unit' => /* @text */'Dinar',
    ),
    'TOP' => array(
        'symbol' => 'T$',
        'name' => /* @text */'Tongan Paʻanga',
        'numeric_code' => '776',
        'minor_unit' => /* @text */'Senit',
        'major_unit' => /* @text */'Paʻanga',
    ),
    'TRY' => array(
        'symbol' => '₺',
        'name' => /* @text */'Turkish Lira',
        'numeric_code' => '949',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => /* @text */'Kurus',
        'major_unit' => /* @text */'Lira',
    ),
    'TTD' => array(
        'symbol' => 'TT$',
        'name' => /* @text */'Trinidad and Tobago Dollar',
        'numeric_code' => '780',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'TWD' => array(
        'symbol' => 'NT$',
        'name' => /* @text */'New Taiwan Dollar',
        'numeric_code' => '901',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'New Dollar',
    ),
    'TZS' => array(
        'symbol' => 'TSh',
        'name' => /* @text */'Tanzanian Shilling',
        'decimals' => 0,
        'numeric_code' => '834',
        'minor_unit' => /* @text */'Senti',
        'major_unit' => /* @text */'Shilling',
    ),
    'UAH' => array(
        'symbol' => 'грн.',
        'name' => /* @text */'Ukrainian Hryvnia',
        'numeric_code' => '980',
        'thousands_separator' => '',
        'decimal_separator' => '.',
        'minor_unit' => /* @text */'Kopiyka',
        'major_unit' => /* @text */'Hryvnia',
    ),
    'UGX' => array(
        'symbol' => 'USh',
        'name' => /* @text */'Ugandan Shilling',
        'decimals' => 0,
        'numeric_code' => '800',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Shilling',
    ),
    'UYU' => array(
        'symbol' => '$U',
        'name' => /* @text */'Uruguayan Peso',
        'numeric_code' => '858',
        'minor_unit' => /* @text */'Centésimo',
        'major_unit' => /* @text */'Peso',
    ),
    'VEF' => array(
        'symbol' => 'Bs.F.',
        'name' => /* @text */'Venezuelan Bolívar Fuerte',
        'minor_unit' => /* @text */'Céntimo',
        'major_unit' => /* @text */'Bolivares Fuerte',
    ),
    'VND' => array(
        'symbol' => 'đ',
        'name' => /* @text */'Vietnamese Dong',
        'decimals' => 0,
        'thousands_separator' => '.',
        'numeric_code' => '704',
        'minor_unit' => /* @text */'Hà',
        'major_unit' => /* @text */'Dong',
    ),
    'VUV' => array(
        'symbol' => 'VT',
        'name' => /* @text */'Vanuatu Vatu',
        'decimals' => 0,
        'numeric_code' => '548',
        'major_unit' => /* @text */'Vatu',
    ),
    'WST' => array(
        'symbol' => 'WS$',
        'name' => /* @text */'Samoan Tala',
        'numeric_code' => '882',
        'minor_unit' => /* @text */'Sene',
        'major_unit' => /* @text */'Tala',
    ),
    'XAF' => array(
        'symbol' => 'FCFA',
        'name' => /* @text */'CFA Franc BEAC',
        'decimals' => 0,
        'numeric_code' => '950',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'XCD' => array(
        'symbol' => 'EC$',
        'name' => /* @text */'East Caribbean Dollar',
        'numeric_code' => '951',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Dollar',
    ),
    'XOF' => array(
        'symbol' => 'CFA',
        'name' => /* @text */'CFA Franc BCEAO',
        'decimals' => 0,
        'numeric_code' => '952',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'XPF' => array(
        'symbol' => 'CFPF',
        'name' => /* @text */'CFP Franc',
        'decimals' => 0,
        'numeric_code' => '953',
        'minor_unit' => /* @text */'Centime',
        'major_unit' => /* @text */'Franc',
    ),
    'YER' => array(
        'symbol' => 'YR',
        'name' => /* @text */'Yemeni Rial',
        'decimals' => 0,
        'numeric_code' => '886',
        'minor_unit' => /* @text */'Fils',
        'major_unit' => /* @text */'Rial',
    ),
    'ZAR' => array(
        'symbol' => 'R',
        'name' => /* @text */'South African Rand',
        'numeric_code' => '710',
        'minor_unit' => /* @text */'Cent',
        'major_unit' => /* @text */'Rand',
    ),
    'ZMK' => array(
        'symbol' => 'ZK',
        'name' => /* @text */'Zambian Kwacha',
        'decimals' => 0,
        'numeric_code' => '894',
        'minor_unit' => /* @text */'Ngwee',
        'major_unit' => /* @text */'Kwacha',
    ),
);

