<?php

/**
 * @package GPL Cart core
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    'USD' => array(
        'symbol' => '$',
        'name' => 'United States Dollar',
        'numeric_code' => '840',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'AED' => array(
        'symbol' => 'د.إ',
        'name' => 'United Arab Emirates Dirham',
        'numeric_code' => '784',
        'minor_unit' => 'Fils',
        'major_unit' => 'Dirham',
    ),
    'AFN' => array(
        'symbol' => 'Af',
        'name' => 'Afghan Afghani',
        'decimals' => 0,
        'numeric_code' => '971',
        'minor_unit' => 'Pul',
        'major_unit' => 'Afghani',
    ),
    'ANG' => array(
        'symbol' => 'NAf.',
        'name' => 'Netherlands Antillean Guilder',
        'numeric_code' => '532',
        'minor_unit' => 'Cent',
        'major_unit' => 'Guilder',
    ),
    'AOA' => array(
        'symbol' => 'Kz',
        'name' => 'Angolan Kwanza',
        'numeric_code' => '973',
        'minor_unit' => 'Cêntimo',
        'major_unit' => 'Kwanza',
    ),
    'ARM' => array(
        'symbol' => 'm$n',
        'name' => 'Argentine Peso Moneda Nacional',
        'minor_unit' => 'Centavos',
        'major_unit' => 'Peso',
    ),
    'ARS' => array(
        'symbol' => 'AR$',
        'name' => 'Argentine Peso',
        'numeric_code' => '032',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'AUD' => array(
        'symbol' => '$',
        'name' => 'Australian Dollar',
        'numeric_code' => '036',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'AWG' => array(
        'symbol' => 'Afl.',
        'name' => 'Aruban Florin',
        'numeric_code' => '533',
        'minor_unit' => 'Cent',
        'major_unit' => 'Guilder',
    ),
    'AZN' => array(
        'symbol' => 'man.',
        'name' => 'Azerbaijanian Manat',
        'minor_unit' => 'Qəpik',
        'major_unit' => 'New Manat',
    ),
    'BAM' => array(
        'symbol' => 'KM',
        'name' => 'Bosnia-Herzegovina Convertible Mark',
        'numeric_code' => '977',
        'minor_unit' => 'Fening',
        'major_unit' => 'Convertible Marka',
    ),
    'BBD' => array(
        'symbol' => 'Bds$',
        'name' => 'Barbadian Dollar',
        'numeric_code' => '052',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'BDT' => array(
        'symbol' => 'Tk',
        'name' => 'Bangladeshi Taka',
        'numeric_code' => '050',
        'minor_unit' => 'Paisa',
        'major_unit' => 'Taka',
    ),
    'BGN' => array(
        'symbol' => 'лв',
        'name' => 'Bulgarian lev',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '975',
        'minor_unit' => 'Stotinka',
        'major_unit' => 'Lev',
    ),
    'BHD' => array(
        'symbol' => 'BD',
        'name' => 'Bahraini Dinar',
        'decimals' => 3,
        'numeric_code' => '048',
        'minor_unit' => 'Fils',
        'major_unit' => 'Dinar',
    ),
    'BIF' => array(
        'symbol' => 'FBu',
        'name' => 'Burundian Franc',
        'decimals' => 0,
        'numeric_code' => '108',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'BMD' => array(
        'symbol' => 'BD$',
        'name' => 'Bermudan Dollar',
        'numeric_code' => '060',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'BND' => array(
        'symbol' => 'BN$',
        'name' => 'Brunei Dollar',
        'numeric_code' => '096',
        'minor_unit' => 'Sen',
        'major_unit' => 'Dollar',
    ),
    'BOB' => array(
        'symbol' => 'Bs',
        'name' => 'Bolivian Boliviano',
        'numeric_code' => '068',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Bolivianos',
    ),
    'BRL' => array(
        'symbol' => 'R$',
        'name' => 'Brazilian Real',
        'numeric_code' => '986',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Reais',
    ),
    'BSD' => array(
        'symbol' => 'BS$',
        'name' => 'Bahamian Dollar',
        'numeric_code' => '044',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'BTN' => array(
        'symbol' => 'Nu.',
        'name' => 'Bhutanese Ngultrum',
        'numeric_code' => '064',
        'minor_unit' => 'Chetrum',
        'major_unit' => 'Ngultrum',
    ),
    'BWP' => array(
        'symbol' => 'BWP',
        'name' => 'Botswanan Pula',
        'numeric_code' => '072',
        'minor_unit' => 'Thebe',
        'major_unit' => 'Pulas',
    ),
    'BYR' => array(
        'symbol' => 'руб.',
        'name' => 'Belarusian ruble',
        'numeric_code' => '974',
        'decimals' => 0,
        'thousands_separator' => ' ',
        'major_unit' => 'Ruble',
    ),
    'BZD' => array(
        'symbol' => 'BZ$',
        'name' => 'Belize Dollar',
        'numeric_code' => '084',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'CAD' => array(
        'symbol' => '$',
        'name' => 'Canadian Dollar',
        'numeric_code' => '124',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'CDF' => array(
        'symbol' => 'CDF',
        'name' => 'Congolese Franc',
        'numeric_code' => '976',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'CHF' => array(
        'symbol' => 'Fr.',
        'name' => 'Swiss Franc',
        'rounding_step' => '0.05',
        'numeric_code' => '756',
        'thousands_separator' => "'",
        'minor_unit' => 'Rappen',
        'major_unit' => 'Franc',
    ),
    'CLP' => array(
        'symbol' => 'CL$',
        'name' => 'Chilean Peso',
        'decimals' => 0,
        'numeric_code' => '152',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'CNY' => array(
        'symbol' => '¥',
        'name' => 'Chinese Yuan Renminbi',
        'numeric_code' => '156',
        'thousands_separator' => '',
        'minor_unit' => 'Fen',
        'major_unit' => 'Yuan',
    ),
    'COP' => array(
        'symbol' => '$',
        'name' => 'Colombian Peso',
        'decimals' => 0,
        'numeric_code' => '170',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'CRC' => array(
        'symbol' => '¢',
        'name' => 'Costa Rican Colón',
        'decimals' => 0,
        'numeric_code' => '188',
        'minor_unit' => 'Céntimo',
        'major_unit' => 'Colón',
    ),
    'CUC' => array(
        'symbol' => 'CUC$',
        'name' => 'Cuban Convertible Peso',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'CUP' => array(
        'symbol' => 'CU$',
        'name' => 'Cuban Peso',
        'numeric_code' => '192',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'CVE' => array(
        'symbol' => 'CV$',
        'name' => 'Cape Verdean Escudo',
        'numeric_code' => '132',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Escudo',
    ),
    'CZK' => array(
        'symbol' => 'Kč',
        'name' => 'Czech Republic Koruna',
        'numeric_code' => '203',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => 'Haléř',
        'major_unit' => 'Koruna',
    ),
    'DJF' => array(
        'symbol' => 'Fdj',
        'name' => 'Djiboutian Franc',
        'numeric_code' => '262',
        'decimals' => 0,
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'DKK' => array(
        'symbol' => 'kr.',
        'name' => 'Danish Krone',
        'numeric_code' => '208',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => 'Øre',
        'major_unit' => 'Kroner',
    ),
    'DOP' => array(
        'symbol' => 'RD$',
        'name' => 'Dominican Peso',
        'numeric_code' => '214',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'DZD' => array(
        'symbol' => 'DA',
        'name' => 'Algerian Dinar',
        'numeric_code' => '012',
        'minor_unit' => 'Santeem',
        'major_unit' => 'Dinar',
    ),
    'EEK' => array(
        'symbol' => 'Ekr',
        'name' => 'Estonian Kroon',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '233',
        'minor_unit' => 'Sent',
        'major_unit' => 'Krooni',
    ),
    'EGP' => array(
        'symbol' => 'EG£',
        'name' => 'Egyptian Pound',
        'numeric_code' => '818',
        'minor_unit' => 'Piastr',
        'major_unit' => 'Pound',
    ),
    'ERN' => array(
        'symbol' => 'Nfk',
        'name' => 'Eritrean Nakfa',
        'numeric_code' => '232',
        'minor_unit' => 'Cent',
        'major_unit' => 'Nakfa',
    ),
    'ETB' => array(
        'symbol' => 'Br',
        'name' => 'Ethiopian Birr',
        'numeric_code' => '230',
        'minor_unit' => 'Santim',
        'major_unit' => 'Birr',
    ),
    'EUR' => array(
        'symbol' => '€',
        'name' => 'Euro',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '978',
        'minor_unit' => 'Cent',
        'major_unit' => 'Euro',
    ),
    'FJD' => array(
        'symbol' => 'FJ$',
        'name' => 'Fijian Dollar',
        'numeric_code' => '242',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'FKP' => array(
        'symbol' => 'FK£',
        'name' => 'Falkland Islands Pound',
        'numeric_code' => '238',
        'minor_unit' => 'Penny',
        'major_unit' => 'Pound',
    ),
    'GBP' => array(
        'symbol' => '£',
        'name' => 'British Pound Sterling',
        'numeric_code' => '826',
        'minor_unit' => 'Penny',
        'major_unit' => 'Pound',
    ),
    'GHS' => array(
        'symbol' => 'GH₵',
        'name' => 'Ghanaian Cedi',
        'minor_unit' => 'Pesewa',
        'major_unit' => 'Cedi',
    ),
    'GIP' => array(
        'symbol' => 'GI£',
        'name' => 'Gibraltar Pound',
        'numeric_code' => '292',
        'minor_unit' => 'Penny',
        'major_unit' => 'Pound',
    ),
    'GMD' => array(
        'symbol' => 'GMD',
        'name' => 'Gambian Dalasi',
        'numeric_code' => '270',
        'minor_unit' => 'Butut',
        'major_unit' => 'Dalasis',
    ),
    'GNF' => array(
        'symbol' => 'FG',
        'name' => 'Guinean Franc',
        'decimals' => 0,
        'numeric_code' => '324',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'GTQ' => array(
        'symbol' => 'GTQ',
        'name' => 'Guatemalan Quetzal',
        'numeric_code' => '320',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Quetzales',
    ),
    'GYD' => array(
        'symbol' => 'GY$',
        'name' => 'Guyanaese Dollar',
        'decimals' => 0,
        'numeric_code' => '328',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'HKD' => array(
        'symbol' => 'HK$',
        'name' => 'Hong Kong Dollar',
        'numeric_code' => '344',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'HNL' => array(
        'symbol' => 'HNL',
        'name' => 'Honduran Lempira',
        'numeric_code' => '340',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Lempiras',
    ),
    'HRK' => array(
        'symbol' => 'kn',
        'name' => 'Croatian Kuna',
        'numeric_code' => '191',
        'minor_unit' => 'Lipa',
        'major_unit' => 'Kuna',
    ),
    'HTG' => array(
        'symbol' => 'HTG',
        'name' => 'Haitian Gourde',
        'numeric_code' => '332',
        'minor_unit' => 'Centime',
        'major_unit' => 'Gourde',
    ),
    'HUF' => array(
        'symbol' => 'Ft',
        'name' => 'Hungarian Forint',
        'numeric_code' => '348',
        'decimal_separator' => ',',
        'thousands_separator' => ' ',
        'decimals' => 0,
        'major_unit' => 'Forint',
    ),
    'IDR' => array(
        'symbol' => 'Rp',
        'name' => 'Indonesian Rupiah',
        'decimals' => 0,
        'numeric_code' => '360',
        'minor_unit' => 'Sen',
        'major_unit' => 'Rupiahs',
    ),
    'ILS' => array(
        'symbol' => '₪',
        'name' => 'Israeli New Shekel',
        'numeric_code' => '376',
        'minor_unit' => 'Agora',
        'major_unit' => 'New Shekels',
    ),
    'INR' => array(
        'symbol' => 'Rs',
        'name' => 'Indian Rupee',
        'numeric_code' => '356',
        'minor_unit' => 'Paisa',
        'major_unit' => 'Rupee',
    ),
    'IRR' => array(
        'symbol' => 'ریال',
        'name' => 'Iranian Rial',
        'decimals' => 0,
        'numeric_code' => '364',
        'minor_unit' => 'Rial',
        'major_unit' => 'Toman',
    ),
    'ISK' => array(
        'symbol' => 'Ikr',
        'name' => 'Icelandic Króna',
        'decimals' => 0,
        'thousands_separator' => ' ',
        'numeric_code' => '352',
        'minor_unit' => 'Eyrir',
        'major_unit' => 'Kronur',
    ),
    'JMD' => array(
        'symbol' => 'J$',
        'name' => 'Jamaican Dollar',
        'numeric_code' => '388',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'JOD' => array(
        'symbol' => 'JD',
        'name' => 'Jordanian Dinar',
        'decimals' => 3,
        'numeric_code' => '400',
        'minor_unit' => 'Piastr',
        'major_unit' => 'Dinar',
    ),
    'JPY' => array(
        'symbol' => '¥',
        'name' => 'Japanese Yen',
        'decimals' => 0,
        'numeric_code' => '392',
        'minor_unit' => 'Sen',
        'major_unit' => 'Yen',
    ),
    'KES' => array(
        'symbol' => 'Ksh',
        'name' => 'Kenyan Shilling',
        'numeric_code' => '404',
        'minor_unit' => 'Cent',
        'major_unit' => 'Shilling',
    ),
    'KGS' => array(
        'symbol' => 'сом',
        'name' => 'Kyrgyzstani Som',
        'numeric_code' => '417',
        'thousands_separator' => '',
        'major_unit' => 'Som',
        'minor_unit' => 'Tyiyn',
    ),
    'KMF' => array(
        'symbol' => 'CF',
        'name' => 'Comorian Franc',
        'decimals' => 0,
        'numeric_code' => '174',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'KRW' => array(
        'symbol' => '₩',
        'name' => 'South Korean Won',
        'decimals' => 0,
        'numeric_code' => '410',
        'minor_unit' => 'Jeon',
        'major_unit' => 'Won',
    ),
    'KWD' => array(
        'symbol' => 'KD',
        'name' => 'Kuwaiti Dinar',
        'decimals' => 3,
        'numeric_code' => '414',
        'minor_unit' => 'Fils',
        'major_unit' => 'Dinar',
    ),
    'KYD' => array(
        'symbol' => 'KY$',
        'name' => 'Cayman Islands Dollar',
        'numeric_code' => '136',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'KZT' => array(
        'symbol' => 'тг.',
        'name' => 'Kazakhstani tenge',
        'numeric_code' => '398',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => 'Tiyn',
        'major_unit' => 'Tenge',
    ),
    'LAK' => array(
        'symbol' => '₭N',
        'name' => 'Laotian Kip',
        'decimals' => 0,
        'numeric_code' => '418',
        'minor_unit' => 'Att',
        'major_unit' => 'Kips',
    ),
    'LBP' => array(
        'symbol' => 'LB£',
        'name' => 'Lebanese Pound',
        'decimals' => 0,
        'numeric_code' => '422',
        'minor_unit' => 'Piastre',
        'major_unit' => 'Pound',
    ),
    'LKR' => array(
        'symbol' => 'SLRs',
        'name' => 'Sri Lanka Rupee',
        'numeric_code' => '144',
        'minor_unit' => 'Cent',
        'major_unit' => 'Rupee',
    ),
    'LRD' => array(
        'symbol' => 'L$',
        'name' => 'Liberian Dollar',
        'numeric_code' => '430',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'LSL' => array(
        'symbol' => 'LSL',
        'name' => 'Lesotho Loti',
        'numeric_code' => '426',
        'minor_unit' => 'Sente',
        'major_unit' => 'Loti',
    ),
    'LTL' => array(
        'symbol' => 'Lt',
        'name' => 'Lithuanian Litas',
        'numeric_code' => '440',
        'minor_unit' => 'Centas',
        'major_unit' => 'Litai',
    ),
    'LVL' => array(
        'symbol' => 'Ls',
        'name' => 'Latvian Lats',
        'numeric_code' => '428',
        'minor_unit' => 'Santims',
        'major_unit' => 'Lati',
    ),
    'LYD' => array(
        'symbol' => 'LD',
        'name' => 'Libyan Dinar',
        'decimals' => 3,
        'numeric_code' => '434',
        'minor_unit' => 'Dirham',
        'major_unit' => 'Dinar',
    ),
    'MAD' => array(
        'symbol' => ' Dhs',
        'name' => 'Moroccan Dirham',
        'numeric_code' => '504',
        'minor_unit' => 'Santimat',
        'major_unit' => 'Dirhams',
    ),
    'MDL' => array(
        'symbol' => 'MDL',
        'name' => 'Moldovan leu',
        'numeric_code' => '498',
        'minor_unit' => 'bani',
        'major_unit' => 'Lei',
    ),
    'MKD' => array(
        'symbol' => 'ден',
        'name' => 'Macedonian denar',
        'numeric_code' => '807',
        'minor_unit' => 'Deni',
        'major_unit' => 'Denari',
    ),
    'MMK' => array(
        'symbol' => 'MMK',
        'name' => 'Myanma Kyat',
        'decimals' => 0,
        'numeric_code' => '104',
        'minor_unit' => 'Pya',
        'major_unit' => 'Kyat',
    ),
    'MNT' => array(
        'symbol' => '₮',
        'name' => 'Mongolian Tugrik',
        'decimals' => 0,
        'numeric_code' => '496',
        'minor_unit' => 'Möngö',
        'major_unit' => 'Tugriks',
    ),
    'MOP' => array(
        'symbol' => 'MOP$',
        'name' => 'Macanese Pataca',
        'numeric_code' => '446',
        'minor_unit' => 'Avo',
        'major_unit' => 'Pataca',
    ),
    'MRO' => array(
        'symbol' => 'UM',
        'name' => 'Mauritanian Ouguiya',
        'decimals' => 0,
        'numeric_code' => '478',
        'minor_unit' => 'Khoums',
        'major_unit' => 'Ouguiya',
    ),
    'MTP' => array(
        'symbol' => 'MT£',
        'name' => 'Maltese Pound',
        'minor_unit' => 'Shilling',
        'major_unit' => 'Pound',
    ),
    'MUR' => array(
        'symbol' => 'MURs',
        'name' => 'Mauritian Rupee',
        'decimals' => 0,
        'numeric_code' => '480',
        'minor_unit' => 'Cent',
        'major_unit' => 'Rupee',
    ),
    'MXN' => array(
        'symbol' => '$',
        'name' => 'Mexican Peso',
        'numeric_code' => '484',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'MYR' => array(
        'symbol' => 'RM',
        'name' => 'Malaysian Ringgit',
        'numeric_code' => '458',
        'minor_unit' => 'Sen',
        'major_unit' => 'Ringgits',
    ),
    'MZN' => array(
        'symbol' => 'MTn',
        'name' => 'Mozambican Metical',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Metical',
    ),
    'NAD' => array(
        'symbol' => 'N$',
        'name' => 'Namibian Dollar',
        'numeric_code' => '516',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'NGN' => array(
        'symbol' => '₦',
        'name' => 'Nigerian Naira',
        'numeric_code' => '566',
        'minor_unit' => 'Kobo',
        'major_unit' => 'Naira',
    ),
    'NIO' => array(
        'symbol' => 'C$',
        'name' => 'Nicaraguan Cordoba Oro',
        'numeric_code' => '558',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Cordoba',
    ),
    'NOK' => array(
        'symbol' => 'Nkr',
        'name' => 'Norwegian Krone',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '578',
        'minor_unit' => 'Øre',
        'major_unit' => 'Krone',
    ),
    'NPR' => array(
        'symbol' => 'NPRs',
        'name' => 'Nepalese Rupee',
        'numeric_code' => '524',
        'minor_unit' => 'Paisa',
        'major_unit' => 'Rupee',
    ),
    'NZD' => array(
        'symbol' => '$',
        'name' => 'New Zealand Dollar',
        'numeric_code' => '554',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'PAB' => array(
        'symbol' => 'B/.',
        'name' => 'Panamanian Balboa',
        'numeric_code' => '590',
        'minor_unit' => 'Centésimo',
        'major_unit' => 'Balboa',
    ),
    'PEN' => array(
        'symbol' => 'S/.',
        'name' => 'Peruvian Nuevo Sol',
        'numeric_code' => '604',
        'minor_unit' => 'Céntimo',
        'major_unit' => 'Nuevos Sole',
    ),
    'PGK' => array(
        'symbol' => 'PGK',
        'name' => 'Papua New Guinean Kina',
        'numeric_code' => '598',
        'minor_unit' => 'Toea',
        'major_unit' => 'Kina ',
    ),
    'PHP' => array(
        'symbol' => '₱',
        'name' => 'Philippine Peso',
        'numeric_code' => '608',
        'minor_unit' => 'Centavo',
        'major_unit' => 'Peso',
    ),
    'PKR' => array(
        'symbol' => 'PKRs',
        'name' => 'Pakistani Rupee',
        'decimals' => 0,
        'numeric_code' => '586',
        'minor_unit' => 'Paisa',
        'major_unit' => 'Rupee',
    ),
    'PLN' => array(
        'symbol' => 'zł',
        'name' => 'Polish Złoty',
        'decimal_separator' => ',',
        'thousands_separator' => ' ',
        'numeric_code' => '985',
        'minor_unit' => 'Grosz',
        'major_unit' => 'Złotych',
    ),
    'PYG' => array(
        'symbol' => '₲',
        'name' => 'Paraguayan Guarani',
        'decimals' => 0,
        'numeric_code' => '600',
        'minor_unit' => 'Céntimo',
        'major_unit' => 'Guarani',
    ),
    'QAR' => array(
        'symbol' => 'QR',
        'name' => 'Qatari Rial',
        'numeric_code' => '634',
        'minor_unit' => 'Dirham',
        'major_unit' => 'Rial',
    ),
    'RHD' => array(
        'symbol' => 'RH$',
        'name' => 'Rhodesian Dollar',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'RON' => array(
        'symbol' => 'RON',
        'name' => 'Romanian Leu',
        'minor_unit' => 'Ban',
        'major_unit' => 'Leu',
    ),
    'RSD' => array(
        'symbol' => 'din.',
        'name' => 'Serbian Dinar',
        'decimals' => 0,
        'minor_unit' => 'Para',
        'major_unit' => 'Dinars',
    ),
    'RUB' => array(
        'symbol' => 'руб.',
        'name' => 'Russian Ruble',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'numeric_code' => '643',
        'minor_unit' => 'Kopek',
        'major_unit' => 'Ruble',
    ),
    'SAR' => array(
        'symbol' => 'SR',
        'name' => 'Saudi Riyal',
        'numeric_code' => '682',
        'minor_unit' => 'Hallallah',
        'major_unit' => 'Riyals',
    ),
    'SBD' => array(
        'symbol' => 'SI$',
        'name' => 'Solomon Islands Dollar',
        'numeric_code' => '090',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'SCR' => array(
        'symbol' => 'SRe',
        'name' => 'Seychellois Rupee',
        'numeric_code' => '690',
        'minor_unit' => 'Cent',
        'major_unit' => 'Rupee',
    ),
    'SDD' => array(
        'symbol' => 'LSd',
        'name' => 'Old Sudanese Dinar',
        'numeric_code' => '736',
        'minor_unit' => 'None',
        'major_unit' => 'Dinar',
    ),
    'SEK' => array(
        'symbol' => 'kr',
        'name' => 'Swedish Krona',
        'numeric_code' => '752',
        'thousands_separator' => ' ',
        'decimal_separator' => ',',
        'minor_unit' => 'Öre',
        'major_unit' => 'Kronor',
    ),
    'SGD' => array(
        'symbol' => 'S$',
        'name' => 'Singapore Dollar',
        'numeric_code' => '702',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'SHP' => array(
        'symbol' => 'SH£',
        'name' => 'Saint Helena Pound',
        'numeric_code' => '654',
        'minor_unit' => 'Penny',
        'major_unit' => 'Pound',
    ),
    'SLL' => array(
        'symbol' => 'Le',
        'name' => 'Sierra Leonean Leone',
        'decimals' => 0,
        'numeric_code' => '694',
        'minor_unit' => 'Cent',
        'major_unit' => 'Leone',
    ),
    'SOS' => array(
        'symbol' => 'Ssh',
        'name' => 'Somali Shilling',
        'decimals' => 0,
        'numeric_code' => '706',
        'minor_unit' => 'Cent',
        'major_unit' => 'Shilling',
    ),
    'SRD' => array(
        'symbol' => 'SR$',
        'name' => 'Surinamese Dollar',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'SRG' => array(
        'symbol' => 'Sf',
        'name' => 'Suriname Guilder',
        'numeric_code' => '740',
        'minor_unit' => 'Cent',
        'major_unit' => 'Guilder',
    ),
    'STD' => array(
        'symbol' => 'Db',
        'name' => 'São Tomé and Príncipe Dobra',
        'decimals' => 0,
        'numeric_code' => '678',
        'minor_unit' => 'Cêntimo',
        'major_unit' => 'Dobra',
    ),
    'SYP' => array(
        'symbol' => 'SY£',
        'name' => 'Syrian Pound',
        'decimals' => 0,
        'numeric_code' => '760',
        'minor_unit' => 'Piastre',
        'major_unit' => 'Pound',
    ),
    'SZL' => array(
        'symbol' => 'SZL',
        'name' => 'Swazi Lilangeni',
        'numeric_code' => '748',
        'minor_unit' => 'Cent',
        'major_unit' => 'Lilangeni',
    ),
    'THB' => array(
        'symbol' => '฿',
        'name' => 'Thai Baht',
        'numeric_code' => '764',
        'minor_unit' => 'Satang',
        'major_unit' => 'Baht',
    ),
    'TND' => array(
        'symbol' => 'DT',
        'name' => 'Tunisian Dinar',
        'decimals' => 3,
        'numeric_code' => '788',
        'minor_unit' => 'Millime',
        'major_unit' => 'Dinar',
    ),
    'TOP' => array(
        'symbol' => 'T$',
        'name' => 'Tongan Paʻanga',
        'numeric_code' => '776',
        'minor_unit' => 'Senit',
        'major_unit' => 'Paʻanga',
    ),
    'TRY' => array(
        'symbol' => '₺',
        'name' => 'Turkish Lira',
        'numeric_code' => '949',
        'thousands_separator' => '.',
        'decimal_separator' => ',',
        'minor_unit' => 'Kurus',
        'major_unit' => 'Lira',
    ),
    'TTD' => array(
        'symbol' => 'TT$',
        'name' => 'Trinidad and Tobago Dollar',
        'numeric_code' => '780',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'TWD' => array(
        'symbol' => 'NT$',
        'name' => 'New Taiwan Dollar',
        'numeric_code' => '901',
        'minor_unit' => 'Cent',
        'major_unit' => 'New Dollar',
    ),
    'TZS' => array(
        'symbol' => 'TSh',
        'name' => 'Tanzanian Shilling',
        'decimals' => 0,
        'numeric_code' => '834',
        'minor_unit' => 'Senti',
        'major_unit' => 'Shilling',
    ),
    'UAH' => array(
        'symbol' => 'грн.',
        'name' => 'Ukrainian Hryvnia',
        'numeric_code' => '980',
        'thousands_separator' => '',
        'decimal_separator' => '.',
        'minor_unit' => 'Kopiyka',
        'major_unit' => 'Hryvnia',
    ),
    'UGX' => array(
        'symbol' => 'USh',
        'name' => 'Ugandan Shilling',
        'decimals' => 0,
        'numeric_code' => '800',
        'minor_unit' => 'Cent',
        'major_unit' => 'Shilling',
    ),
    'UYU' => array(
        'symbol' => '$U',
        'name' => 'Uruguayan Peso',
        'numeric_code' => '858',
        'minor_unit' => 'Centésimo',
        'major_unit' => 'Peso',
    ),
    'VEF' => array(
        'symbol' => 'Bs.F.',
        'name' => 'Venezuelan Bolívar Fuerte',
        'minor_unit' => 'Céntimo',
        'major_unit' => 'Bolivares Fuerte',
    ),
    'VND' => array(
        'symbol' => 'đ',
        'name' => 'Vietnamese Dong',
        'decimals' => 0,
        'thousands_separator' => '.',
        'numeric_code' => '704',
        'minor_unit' => 'Hà',
        'major_unit' => 'Dong',
    ),
    'VUV' => array(
        'symbol' => 'VT',
        'name' => 'Vanuatu Vatu',
        'decimals' => 0,
        'numeric_code' => '548',
        'major_unit' => 'Vatu',
    ),
    'WST' => array(
        'symbol' => 'WS$',
        'name' => 'Samoan Tala',
        'numeric_code' => '882',
        'minor_unit' => 'Sene',
        'major_unit' => 'Tala',
    ),
    'XAF' => array(
        'symbol' => 'FCFA',
        'name' => 'CFA Franc BEAC',
        'decimals' => 0,
        'numeric_code' => '950',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'XCD' => array(
        'symbol' => 'EC$',
        'name' => 'East Caribbean Dollar',
        'numeric_code' => '951',
        'minor_unit' => 'Cent',
        'major_unit' => 'Dollar',
    ),
    'XOF' => array(
        'symbol' => 'CFA',
        'name' => 'CFA Franc BCEAO',
        'decimals' => 0,
        'numeric_code' => '952',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'XPF' => array(
        'symbol' => 'CFPF',
        'name' => 'CFP Franc',
        'decimals' => 0,
        'numeric_code' => '953',
        'minor_unit' => 'Centime',
        'major_unit' => 'Franc',
    ),
    'YER' => array(
        'symbol' => 'YR',
        'name' => 'Yemeni Rial',
        'decimals' => 0,
        'numeric_code' => '886',
        'minor_unit' => 'Fils',
        'major_unit' => 'Rial',
    ),
    'ZAR' => array(
        'symbol' => 'R',
        'name' => 'South African Rand',
        'numeric_code' => '710',
        'minor_unit' => 'Cent',
        'major_unit' => 'Rand',
    ),
    'ZMK' => array(
        'symbol' => 'ZK',
        'name' => 'Zambian Kwacha',
        'decimals' => 0,
        'numeric_code' => '894',
        'minor_unit' => 'Ngwee',
        'major_unit' => 'Kwacha',
    ),
);

