<?php

/**
 * @package GPL Cart core
 * @author Iurii Makukh <gplcart.software@gmail.com>
 * @copyright Copyright (c) 2015, Iurii Makukh
 * @license https://www.gnu.org/licenses/gpl.html GNU/GPLv3
 */
return array(
    'admin' => 'Admin: access', // @text
    'address' => 'Address: access', // @text
    'address_delete' => 'Address: delete', // @text
    'bookmark' => 'Bookmark: access', // @text
    'bookmark_add' => 'Bookmark: add', // @text
    'bookmark_delete' => 'Bookmark: delete', // @text
    'cart' => 'Cart items: access', // @text
    'cart_delete' => 'Cart items: delete', // @text
    'cli' => 'CLI: access', // @text
    'dashboard' => 'Dashboard: access', // @text
    'dashboard_edit' => 'Dashboard: edit', // @text
    'product' => 'Product: access', // @text
    'product_add' => 'Product: add', // @text
    'product_edit' => 'Product: edit', // @text
    'product_delete' => 'Product: delete', // @text
    'product_class' => 'Product class: access', // @text
    'product_class_add' => 'Product class: add', // @text
    'product_class_edit' => 'Product class: edit', // @text
    'product_class_delete' => 'Product class: delete', // @text
    'product_bundle_edit' => 'Product bundle: edit', // @text
    'price_rule' => 'Price rule: access', // @text
    'price_rule_add' => 'Price rule: add', // @text
    'price_rule_edit' => 'Price rule: edit', // @text
    'price_rule_delete' => 'Price rule: delete', // @text
    'page' => 'Page: access', // @text
    'page_add' => 'Page: add', // @text
    'page_edit' => 'Page: edit', // @text
    'page_delete' => 'Page: delete', // @text
    'review' => 'Review: access', // @text
    'review_add' => 'Review: add', // @text
    'review_edit' => 'Review: edit', // @text
    'review_delete' => 'Review: delete', // @text
    'category' => 'Category: access', // @text
    'category_add' => 'Category: add', // @text
    'category_edit' => 'Category: edit', // @text
    'category_delete' => 'Category: delete', // @text
    'category_group' => 'Category group: access', // @text
    'category_group_add' => 'Category group: add', // @text
    'category_group_edit' => 'Category group: edit', // @text
    'category_group_delete' => 'Category group: delete', // @text
    'collection' => 'Collection: access', // @text
    'collection_add' => 'Collection: add', // @text
    'collection_edit' => 'Collection: edit', // @text
    'collection_delete' => 'Collection: delete', // @text
    'collection_item' => 'Collection item: access', // @text
    'collection_item_add' => 'Collection item: add', // @text
    'collection_item_edit' => 'Collection item: edit', // @text
    'collection_item_delete' => 'Collection item: delete', // @text
    'user' => 'User: access', // @text
    'user_add' => 'User: add', // @text
    'user_edit' => 'User: edit', // @text
    'user_delete' => 'User: delete', // @text
    'user_role' => 'User role: access', // @text
    'user_role_add' => 'User role: add', // @text
    'user_role_edit' => 'User role: edit', // @text
    'user_role_delete' => 'User role: delete', // @text
    'field' => 'Field: access', // @text
    'field_edit' => 'Field: edit', // @text
    'field_add' => 'Field: add', // @text
    'field_delete' => 'Field: delete', // @text
    'field_value' => 'Field value: access', // @text
    'field_value_edit' => 'Field value: edit', // @text
    'field_value_add' => 'Field value: add', // @text
    'field_value_delete' => 'Field value: delete', // @text
    'order' => 'Order: access', // @text
    'order_add' => 'Order: add', // @text
    'order_edit' => 'Order: edit', // @text
    'order_delete' => 'Order: delete', // @text
    'maintenance' => 'Maintenance: access', // @text
    'module' => 'Module: access', // @text
    'module_edit' => 'Module: configure', // @text
    'module_install' => 'Module: install', // @text
    'module_uninstall' => 'Module: uninstall', // @text
    'module_enable' => 'Module: enable', // @text
    'module_disable' => 'Module: disable', // @text
    'store' => 'Store: access', // @text
    'store_edit' => 'Store: edit', // @text
    'store_add' => 'Store: add', // @text
    'store_delete' => 'Store: delete', // @text
    'image_style' => 'Image style: access', // @text
    'image_style_edit' => 'Image style: edit', // @text
    'image_style_add' => 'Image style: add', // @text
    'image_style_delete' => 'Image style: delete', // @text
    'language' => 'Language: access', // @text
    'language_add' => 'Language: add', // @text
    'language_edit' => 'Language: edit', // @text
    'language_delete' => 'Language: delete', // @text
    'currency' => 'Currency: access', // @text
    'currency_add' => 'Currency: add', // @text
    'currency_edit' => 'Currency: edit', // @text
    'currency_delete' => 'Currency: delete', // @text
    'country' => 'Country: access', // @text
    'country_edit' => 'Country: edit', // @text
    'country_add' => 'Country: add', // @text
    'country_delete' => 'Country: delete', // @text
    'country_format' => 'Country format: access', // @text
    'country_format_edit' => 'Country format: edit', // @text
    'state' => 'Country state: access', // @text
    'state_add' => 'Country state: add', // @text
    'state_edit' => 'Country state: edit', // @text
    'state_delete' => 'Country state: delete', // @text
    'transaction' => 'Transaction: access', // @text
    'transaction_delete' => 'Transaction: delete', // @text
    'trigger' => 'Trigger: access', // @text
    'trigger_add' => 'Trigger: add', // @text
    'trigger_edit' => 'Trigger: edit', // @text
    'trigger_delete' => 'Trigger: delete', // @text
    'city' => 'City: access', // @text
    'city_add' => 'City: add', // @text
    'city_edit' => 'City: edit', // @text
    'city_delete' => 'City: delete', // @text
    'report' => 'Report: access', // @text
    'report_events' => 'Report system events: access', // @text
    'report_status' => 'Report system status: access', // @text
    'report_library' => 'Report libraries: access', // @text
    'file' => 'File: access', // @text
    'file_add' => 'File: add', // @text
    'file_edit' => 'File: edit', // @text
    'file_delete' => 'File: delete', // @text
    'file_upload' => 'File: upload', // @text
    'settings' => 'Settings: access', // @text
    'alias' => 'URL alias: access', // @text
    'alias_delete' => 'URL alias: delete', // @text
    'zone' => 'Zone: access', // @text
    'zone_edit' => 'Zone: edit', // @text
    'zone_add' => 'Zone: add', // @text
    'zone_delete' => 'Zone: delete', // @text
);
